Updated platform upgrade script.

diff --git a/platform-upgrade b/platform-upgrade
--- a/platform-upgrade
+++ b/platform-upgrade
@@ -8,40 +8,21 @@ platform_dir="platform-$version"
 platform_url="$host$latest_path/$platform_file"
 md5sums_url="$host$latest_path/md5sums.txt"
 
+force=false
+while getopts 'f' option; do
+	case "$option" in
+		f) force=true;;
+	esac
+done
+
+IFS=_ read brand kernel < <(uname -v)
+if [[ $kernel == $version ]]; then
+	echo "already on latest version: $kernel"
+	$force || exit -1
+fi
+
 tmp=$(mktemp -d)
 cd "$tmp" || exit -1
-
-echo -n "Checking current boot device..."
-if [[ -z $1 ]] ; then
-        removables=($(disklist -r))
-        echo -n " detected ${removables[@]}"
-        if [[ ${#removables[@]} -gt 1 ]]; then
-                  echo
-                  echo "Error: more than one removable device detected."
-		  echo "Specify correct device on the command line."
-                  exit -1
-        fi
-	usb="/dev/dsk/${removables[0]}p1"
-else
-        usb="$1"
-        echo -n " using $usb"
-fi
-
-umount "$usb" 2>/dev/null
-mkdir usb
-if ! mount -F pcfs -o foldcase "$usb" "$tmp/usb" ; then
-        echo ", mount failed"
-        exit -1
-else
-        echo -n ", mounted"
-fi
-
-if [[ ! -d usb/platform ]] ; then
-        echo ", missing platform dir"
-        exit -1
-else
-        echo ", OK"
-fi
 
 echo -n "Downloading latest platform ($platform_file)..."
 if ! curl -sk -o "$platform_file" "$platform_url" ; then
@@ -69,6 +50,46 @@ if ! gtar zxf "$platform_file" ; then
         exit -1
 else
         echo " OK"
+fi
+
+echo -n "Marking release version..."
+if ! echo $version > $platform_dir/VERSION ; then
+        echo " failed"
+        exit -1
+else
+        echo " OK"
+fi
+
+echo -n "Checking current boot device..."
+if [[ -z $1 ]] ; then
+        removables=($(disklist -r))
+        echo -n " detected ${removables[@]}"
+        if [[ ${#removables[@]} -gt 1 ]]; then
+                  echo
+                  echo "Error: more than one removable device detected."
+                  echo "Specify correct device on the command line."
+                  exit -1
+        fi
+        usb="/dev/dsk/${removables[0]}p1"
+else
+        usb="$1"
+        echo -n " using $usb"
+fi
+
+umount "$usb" 2>/dev/null
+mkdir usb
+if ! mount -F pcfs -o foldcase "$usb" "$tmp/usb" ; then
+        echo ", mount failed"
+        exit -1
+else
+        echo -n ", mounted"
+fi
+
+if [[ ! -d usb/platform ]] ; then
+        echo ", missing platform dir"
+        exit -1
+else
+        echo ", OK"
 fi
 
 echo -n "Updating platform on boot device..."
